# Generated by Django 5.2.4 on 2025-07-12 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDataSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(help_text='Название сайта', max_length=255)),
                ('tg_chat_id', models.CharField(blank=True, help_text='ID отправки формы в TG', max_length=32, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Контактный email', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Телефон', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Адрес', null=True)),
                ('logo_footer', models.ForeignKey(blank=True, help_text='Рекомендуемый размер: 180×50 пикселей', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип в подвале')),
                ('logo_header', models.ForeignKey(blank=True, help_text='Рекомендуемый размер: 180×50 пикселей', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Логотип в шапке')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Данные сайта',
            },
        ),
    ]
