# Generated by Django 5.2.4 on 2025-07-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingssite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedatasettings',
            name='robots',
            field=models.TextField(blank=True, help_text='robots.txt', null=True),
        ),
    ]
