# Generated by Django 5.2.4 on 2025-07-12 04:34

import blog.models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorContainer',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogCatalog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 заголовок')),
                ('keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевые слова')),
                ('seo_text', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='SEO текст')),
                ('posts_per_page', models.PositiveIntegerField(default=6, verbose_name='Количество постов на странице')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', blog.models.PaginationMixin, blog.models.CategoriesMixin),
        ),
        migrations.CreateModel(
            name='BlogCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 заголовок')),
                ('keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевые слова')),
                ('seo_text', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='SEO текст')),
                ('posts_per_page', models.PositiveIntegerField(default=6, verbose_name='Количество постов на странице')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', blog.models.PaginationMixin, blog.models.CategoriesMixin),
        ),
        migrations.CreateModel(
            name='AuthorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 заголовок')),
                ('keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевые слова')),
                ('education', models.CharField(blank=True, max_length=128)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', blog.models.PostMixin),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 заголовок')),
                ('keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевые слова')),
                ('intro', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('authors', modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.authorpage', verbose_name='Авторы')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', blog.models.PostMixin),
        ),
    ]
