# Generated by Django 5.2.4 on 2025-07-06 02:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcatalog',
            name='seo_text',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='SEO текст'),
        ),
    ]
