# Generated by Django 5.2.4 on 2025-07-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcatalog_seo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcatalog',
            name='h1',
            field=models.CharField(blank=True, max_length=255, verbose_name='H1 заголовок'),
        ),
        migrations.AddField(
            model_name='blogcatalog',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, verbose_name='Ключевые слова'),
        ),
    ]
