# Generated by Django 5.2.4 on 2025-07-06 03:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcatalog_h1_blogcatalog_keywords'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1', models.CharField(blank=True, max_length=255, verbose_name='H1 заголовок')),
                ('keywords', models.CharField(blank=True, max_length=512, verbose_name='Ключевые слова')),
                ('intro', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Тело поста')),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
