# Generated by Django 5.2.4 on 2025-07-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Рубрика блога', 'verbose_name_plural': 'Рубрики блога'},
        ),
    ]
