# Generated by Django 5.2.4 on 2025-07-06 05:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcategory_options'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1', models.CharField(blank=True, max_length=255, verbose_name='H1 заголовок')),
                ('keywords', models.CharField(blank=True, max_length=512, verbose_name='Ключевые слова')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
