# Generated by Django 5.2.4 on 2025-07-06 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcategorypage_remove_blogpost_categories_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcatalog',
            name='posts_per_page',
            field=models.PositiveIntegerField(default=6, verbose_name='Количество постов на странице'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
