# Generated by Django 5.2.4 on 2025-07-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcatalog_posts_per_page_blogpost_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorypage',
            name='posts_per_page',
            field=models.PositiveIntegerField(default=6, verbose_name='Количество постов на странице'),
        ),
    ]
