# Generated by Django 5.2.4 on 2025-07-06 09:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_authorpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='education',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
