# Generated by Django 5.2.4 on 2025-07-06 09:47

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_authorpage_bio_authorpage_education_authorpage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.authorpage', verbose_name='Авторы'),
        ),
    ]
