# Generated by Django 5.2.4 on 2025-07-12 04:34

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 заголовок')),
                ('keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевые слова')),
                ('about_text', wagtail.fields.RichTextField(blank=True, verbose_name='Текст о компании')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 заголовок')),
                ('keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевые слова')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 заголовок')),
                ('keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевые слова')),
                ('hero_text', wagtail.fields.RichTextField(blank=True, verbose_name='Текст на главной')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 заголовок')),
                ('keywords', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевые слова')),
                ('privacy_text', wagtail.fields.RichTextField(blank=True, verbose_name='Текст политики')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
